spring:
  datasource:
    url: jdbc:postgresql://localhost:8032/beam_db
    username: pguser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
