networks:
  public_net:
    driver: bridge
  private_net:
    driver: bridge
    internal: true

volumes:
  mysql_data:
  postgres_data:

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8032:${POSTGRES_PORT}"
    networks:
      - private_net
      - public_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d pulse_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  config-server:
    image: thilankaw/netrics/config-server:0.0.1
    expose:
      - "8003"
    environment:
      - CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
      - DISCOVERY_HOST=${DISCOVERY_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8003/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - private_net

  discovery:
    image: thilankaw/netrics/discovery:0.0.1
    expose:
      - "8761"
    environment:
      - DISCOVERY_HOST=${DISCOVERY_HOST}
      - CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - private_net
    restart: unless-stopped

  gateway:
    image: thilankaw/netrics/gateway:0.0.1
    ports:
      - "8001:8001"
    expose:
      - "9001"
    environment:
      - GATEWAY_HOST=${GATEWAY_HOST}
      - CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
      - DISCOVERY_HOST=${DISCOVERY_HOST}
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9001/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      discovery:
        condition: service_healthy
      pulse:
        condition: service_healthy
    networks:
      - private_net
      - public_net

  pulse:
    image: thilankaw/netrics/pulse:0.0.2
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PULSE_HOST=${PULSE_HOST}
      - CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}
      - DISCOVERY_HOST=${DISCOVERY_HOST}
    expose:
      - "8012"
      - "9012"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9012/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      discovery:
        condition: service_healthy
    networks:
      - private_net

  kpip-ltefdd-day:
    image: thilankaw/netrics/kpip-ltefdd-day:0.0.3
    container_name: kpip-ltefdd-day
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      pulse:
        condition: service_healthy
    volumes:
#      - ./backend/python/pulse/files/day-average/ltefdd/ftp:/app/day-average/ltefdd/ftp
#      - ./backend/python/pulse/files/day-average/ltefdd/processed:/app/day-average/ltefdd/processed
#      - ./backend/python/pulse/files/day-average/ltefdd/temp:/app/day-average/ltefdd/temp
#      - ./backend/python/pulse/files/day-average/ltefdd/logs:/app/day-average/ltefdd/logs
#      - ./backend/python/pulse/config-ltefdd-day.json:/app/config-ltefdd-day.json
      - /home/ftpuser/THILANKAW/netrics/backend/python/pulse/files/day-average/ltefdd/ftp:/app/day-average/ltefdd/ftp
      - /home/ftpuser/THILANKAW/netrics/backend/python/pulse/files/day-average/ltefdd/processed:/app/day-average/ltefdd/processed
      - /home/ftpuser/THILANKAW/netrics/backend/python/pulse/files/day-average/ltefdd/temp:/app/day-average/ltefdd/temp
      - /home/ftpuser/THILANKAW/netrics/backend/python/pulse/files/day-average/ltefdd/logs:/app/day-average/ltefdd/logs
      - /home/ftpuser/THILANKAW/netrics/backend/python/pulse/files/day-average/ltefdd/config-ltefdd-day.json:/app/config-ltefdd-day.json
    networks:
      - private_net

  frontend:
    container_name: frontend
    image: thilankaw/netrics/frontend:0.0.2
    ports:
      - "8000:80"   # Remember to Enable CORS in BeansConfig for localhost:4200
    networks:
      - public_net
    depends_on:
      gateway:
        condition: service_healthy