spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: pulse-service
              uri: lb:http://PULSE-SERVICE
              predicates:
                - Path=/api/v1/pulse/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://172.19.95.160:4200"
                  - "http://172.19.95.160:8000"
                  - "http://localhost:4200"
                  - "http://localhost:8000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600  # Cache preflight response for 1 hour
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${DOMAIN_IP:localhost}:${FRONTEND_PORT:8000}/auth/realms/${REALM_NAME:netrics}
            authorization-uri: http://${DOMAIN_IP:localhost}:${FRONTEND_PORT:8000}/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/certs
            user-name-attribute: preferred_username

        registration:
          keycloak:
            provider: keycloak
            client-id: ${GATEWAY_CLIENT_ID:netrics-gateway}
            client-secret: ${GATEWAY_CLIENT_SECRET:BDKXS279Zt7pYLcOFJ2ENMNqw3Gi8bRt}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

      resourceserver:
        jwt:
          issuer-uri: http://${DOMAIN_IP:localhost}:${FRONTEND_PORT:8000}/auth/realms/${REALM_NAME:netrics}
          jwk-set-uri: http://keycloak:8080/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/certs

server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true #To force Eureka to use host IP address instead of PC Name
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/

management:   # Configurations for Actuator
  endpoints:
    web:
      exposure:
        include: health,info # only expose safe endpoints
  endpoint:
    health:
      show-details: never # don’t leak DB status, etc.
  server:
    port: 9001 # separate internal port for actuator