spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: pulse-service
#          uri: lb:http://PULSE-SERVICE
#          predicates:
#            - Path=/api/v1/pulse/**
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: pulse-service
              uri: lb:http://PULSE-SERVICE
              predicates:
                - Path=/api/v1/pulse/**

server:
  port: 8001