server:
  port: 8012
eureka:
  instance:
    prefer-ip-address: true #To force Eureka to use host IP address instead of PC Name
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/
spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8000}/auth/realms/${REALM_NAME:netrics}

          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8000}/auth/realms/${REALM_NAME:netrics}/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8000}/auth/realms/${REALM_NAME:netrics}
        registration:
          keycloak:
            client-id: ${PULSE_CLIENT_ID:netrics-pulse}
            client-secret: ${PULSE_CLIENT_SECRET:dep1VnzCyQ0WJgGfCMmVP0fDUw9LnSTn}
            authorization-grant-type: client_credentials
            scope:
              - openid
  flyway:
    baseline-on-migrate: true
    enable: true

  kafka:
#    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  # keeps messages clean
    consumer:
      group-id: beam-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.thilanka.netrics,dev.thilanka.beam"
    topic:
      site-events: beam.site.events
      sector-events: beam.sector.events
      band-events: pulse.band.events

keycloak:
  realm-name: ${REALM_NAME:netrics}
  domain-ip: ${DOMAIN_IP:netrics.local}
  nginx-port: ${FRONTEND_PORT:8000}
  keycloak-host: ${KEYCLOAK_HOST:netrics.local}
  keycloak-port: ${KEYCLOAK_PORT:8000}

caching:
  async:
    core-pool-size: ${CORE_POOL_SIZE:3}
    max-pool-size: ${MAX_POOL_SIZE:6}
    queue-capacity: ${QUEUE_CAPACITY:50}
app:
  worst-cell-dashboard:
    refresh-day: ${REFRESH_DAY:TUESDAY}

management:
  endpoints:
    web:
      exposure:
        include: health,info  # only expose safe endpoints
  endpoint:
    health:
      show-details: never   # don’t leak DB status, etc.
  server:
    port: 9012