spring:
  datasource:
    url: jdbc:mysql://localhost:8006/netrics_pulse_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
